# -*- coding: utf-8-unix; -*-
#+TITLE:       国共两党入党誓词
#+AUTHOR:      Bruce Asu
#+EMAIL:       bruceasu@163.com
#+DATE:        <2010-10-01 20:00>
#+filetags:    people
#+DESCRIPTION: 从誓词中，可以看到一个政党的宗旨和代表力量，党组织、国家和人民在行动中的地位。

#+LANGUAGE:    en
#+OPTIONS:     H:7 num:nil toc:nil \n:nil ::t |:t ^:nil -:nil f:t *:t <:nil

从誓词中，可以看到一个政党的宗旨和代表力量，党组织、国家和人民在行动中的地位。

* 共产党
中国共产党的历史上，各个时期入党誓词有所不同。
** 1、红军时期入党誓词： 1 个党字， 0 个民字，0 个国字
严守秘密，服从纪律，牺牲个人，阶级斗争，努力革命，永不叛 *党* 。
** 2、抗日战争时期入党誓词：2 个党字，0 个民字，0 个国字
我志愿加入中国共产 *党* ，坚持执行 *党* 的纪律，不怕困难，不怕牺牲，为共产主义事
业奋斗到底。
** 3、解放战争时期入党誓词： 7 个党字，0 个民字，0 个国字
我志愿加入中国共产 *党* ，作如下宣誓：
- 一、 终身为共产主义事业奋斗。
- 二、 *党* 的利益高于一切。
- 三、 遵守 *党* 的纪律。
- 四、 不怕困难，永远为 *党* 工作。
- 五、 要做群众的模范。
- 六、 保守 *党* 的秘密。
- 七、 对 *党* 有信心。
- 八、 百折不挠永不叛 *党* 。
** 4、新中国成立初期入党誓词：5 个党字， 0 个民字，0 个国字
我志愿加入中国共产 *党* ，承认 *党* 纲党章，执行 *党* 的决议，遵守 *党* 的纪律，保守
*党* 的秘密，随时准备牺牲个人一切，为全人类彻底解放奋斗终身。
** 5、党的十二大以后入党誓词：10 个党字，1 个民字，0 个国字
我志愿加入中国共产 *党* ，拥护 *党* 的纲领，遵守 *党* 的章程，履行 *党* 员义务，执行
*党* 的决定，严守 *党* 的纪律，保守 *党* 的秘密，对 *党* 忠诚，积极工作，为共产主义
奋斗终身，随时准备为 *党* 和人 *民* 牺牲一切，永不叛 *党*。

* 国民党

誓词：其中：4 个党字， 8 个民字， 16 个国字

总理立承先启后救国救民之大志，创造三民主义五权宪法之宏规，领导国民革命，兴中
华，建民国，于今全国同胞，皆能一德一心，共承遗教者，斯乃我总理大智大仁大勇之
所化，亦即中国列祖列宗所遗天下为公大道大德之所感。

今革命基础大立，革命主义大行，而内忧外患，与革命之进展，同时加重。凡我同志，
应知吾党上对亿万世之祖宗，下对亿万世之后代，中对全国国民与世界人类，所负之责
任，更千百倍于往昔。

我总理深知国者人之积，人者心之器，国家之治乱，系于社会之隆污，社会之隆污，系
于人心之振靡。又知往古圣人诚正修齐治平之一贯大道，与修身为本之唯一至德，为救
国救民救济全世界人类之无上要义，故不惮于遗教中，再四谆谆告诫。

本大会懔于遗教之伟大深切，与国难之严重，更鉴于世界人类祸患之方兴未已，确信自
立为立人之基，自救为救人之始。特制为全党党员守则十二条，通令全体同志，一致遵
行。务期父以教子，师以教弟，长官以教属僚，将帅以教士兵，共信共行，互切互磋，
亲爱精诚，始终无间。

人人能成为世界上顶天立地之人，斯中华民国成为世界上富强康乐之国，然后三民主义
能实行于全国，弘扬于世界，千年万世，永垂无疆之休。惟我负革命建国大责重任之全
党同志共守之。

- 一、 忠勇为爱国之本
- 二、 孝顺为齐家之本
- 三、 仁爱为接物之本
- 四、 信义为立业之本
- 五、 和平为处世之本
- 六、 礼节为治事之本
- 七、 服从为负责之本
- 八、 勤俭为服务之本
- 九、 整洁为强身之本
- 十、 助人为快乐之本
- 十一、 学问为济世之本
- 十二、 有恒为成功之本
