# -*- org -*-
#+OPTIONS: ^:{}
#+TITLE: 互联网产品设计常用文档类型BRD、MRD、PRD、FSD
#+date: <2016-08-17 20:48>
#+filetags: reprint

* BRD、MRD、PRD一起被认为是从市场到产品需要建立的文档规范。

BRD 商业需求文档——BRD（Business Requirements Document）商业需求文档重
点放在定义产品的商业需求，要说明产品能够解决的、客户碰到的一个或多个商
业问题，然后提出建议解决方案——通常是用新产品或者改进现有的产品来解决这
些问题。  BRD也可能包括一个高级的商业案例，例如收益预测、 市场&竞争分
析、 销售/市场策略。  BRD通常是由产品经理，产品市场经理、商业分析师编
写。在小公司，可能由高级主管或者甚至创始人撰写。

- BRD通常是一份 1~3页 Word 文档，或者是不超过 10页的 PowerPoint 文档。

- PRD 产品需求文档 (Product Requirement Document，PRD)的英文简称。是将商
业需求文档（BRD）和市场需求文档（MRD）用更加专业的语言进行描述。

  - 文档作用 :: 该文档是产品项目由“概念化”阶段进入到“图纸化”阶段的最主要的一个文
            档，其作用就是“对MRD中的内容进行指标化和技术化”，这个文档的质量好坏
            直接影响到研发部门是否能够明确产品的功能和性能。

  - 文档意义 :: 该文档在产品项目中是一个“承上启下”的作用，“向上”是对MRD内容的继
            承和发展，“向下”是要把MRD中的内容技术化，向研发部门说明产品的功能和
            性能指标。

  - 文档撰写 :: 在该文档中，基点依然是MRD中的内容，只是把重心放在了“产品需求”上，
            而产品需求本身实在MRD中有所体现的，区别就是在于，PRD要把MRD中的“产品
            需求”的内容独立出来加以详细的说明。

  - 文档核心 :: 该文档中，侧重的是对产品产品功能和性能（即“产品需求”）的说明，相
            对于MRD中的同样内容，要更加详细，并进行量化。在一些国外的公司，是允
            许把MRD和PRD合并成一个文档的，通常叫做“Marketing & Product
            Requirements Document”。

* 错误认识
1) PRD无原始数据（MRD为体现载体）支持，只是个人经验、部门要求或者领导指示进行撰
   写。
2) 在PRD中，只重视“产品功能”的描述，而缺乏对产品其它指标项的说明。在一个完整的
   PRD中，一共需要对产品的10个产品需求项指标进行说明，分别是“功能要求、开发要求、
   兼容性要求、性能要求、扩展要求、产品文档要求、产品外观要求、产品发布要求、产
   品支持和培训要求、产品其它要求”。
3) 照搬国外的PRD模板，来源于何处，不知道，将去向何处，也不知道，无头无尾，一个被
   割裂的文档。

* 定义

- MRD :: Market Requirements Document,简称市场需求文档。市场需求文档的主要功能是
         描述什么样的功能和特点的产品（包含产品版本）可以在市场上取得成功。产品
         进入实施，需要先出MRD，具体来说要有更细致的市场与竞争对手分析，通过哪些
         功能来实现商业目的，功能/非功能需求分哪几块，功能的优先级等等。实际工作
         中，这个阶段PD可能的产出物有Mind Manager的思维图，Excel的Feature List等。

         产品市场经理（PMM，Product Marketing Manager）负责分析市场变化，通过对
         市场的分析，MRD指出什么样的新产品、方案和服务可以更好的开拓市场。

         通常情况下，产品经理或者技术产品经理会将在MRD的基础上完成PRD（Product
         Requiremnets Document），技术团队应用PRD开发产品

- BRD :: Business Requirements Document，商业需求文档。这是产品声明周期中最早的
         问的文档，再早就应该是脑中的构思了，其内容涉及市场分析，销售策略，盈利
         预测等，通常是和老大们过的ppt，所以也就比较短小精炼，没有产品细节。

         商业需求文档重点放在定义项目的商业需求。BRD要能说出客户碰到的一个或多个
         商业问题，并且通过公司的产品能够解决这些问题。接着建议一个方案 —— 通常
         是新产品或者现有产品的改进来解决这些问题。BRD也可能包括一个高级的商业案
         例，例如收益预测，市场竞争分析和销售/营销策略。BRD通常是由拥有产品经理，
         产品营销经理或者行业分析师头衔的人撰写的。在小公司，可能由高级主管或者
         甚至创始人撰写。BRD通常是一份连续的1-3页Word文档，或者不超过10页的
         Powerpoint文档。

- MRD :: Market Requirements Document，市场需求文档。获得老大的认同后，产品进入
         实施，需要先出MRD，具体来说要有更细致的市场与竞争对手分析，通过哪些功能
         来实现商业目的，功能/非功能需求分哪几块，功能的优先级等等。实际工作中，
         这个阶段PD可能的产出物有Mind Manager的思维图，Excel的Feature List等。

         市场需求文档（MRD）重点放在为一个被提议的新产品或者现有产品的
         改进定义市场需求。与BRD指出商业问题和解决这些问题的解决方案不
         同，MRD更深入提议解决方案的细节。它包括一些或者所有这些细节：
         #+BEGIN_VERSE
         a. 解决商业问题所需要的特色
         b. 市场竞争分析
         c. 功能和非功能需求
         d. 特色/需求的优先级
         e. 用例

         #+END_VERSE

        MRD通常是由拥有产品经理，产品营销经理或者行业分析师头衔的人撰写的。MRD通
         常是一份连续的5-25页Word文档，或者正如之后描述那样在一些机构中甚至更长。

- PRD :: Product Requirements Document，产品需求文档。进步一细化，这部分是PD写得
         最多的内容，也就是传统意义上的需求分析，我们这里主要指UC（use case）文
         档。主要内容有，功能使用的具体描述（每个UC一般有用例简述、行为者、前置
         条件、后置条件、UI描述、流程/子流程/分支流程，等几大块），Visio做的功能
         点业务流程，界面的说明，demo等。Demo方面，可能用dreamweaver、ps甚至画图
         板简单画一下，有时候也会有UI/UE支持，出高保真的demo，开发将来可以直接用
         的那种。

         产品需求文档（PRD）重点放在为一个被提议的新产品或者现有产品的改进定义市
         场需求。与MRD侧重于从市场需要角度看需求的不同，PRD侧重于从产品本身角度
         看待需求。通常在特点和功能需求上更深入细节，并也可能包括屏幕截图和用户
         界面流程。在那些MRD不包括具体需求和用例的机构中，PRD就包含这些具体内容。
         PRD通常是由拥有产品经理，行业分析师或者产品分析师头衔的人撰写的。PRD通
         常是一份连续的20-50页Word文档，或者针对复杂产品甚至更长。

         提醒：一些机构将这里描述的MRD和PRD合并成一个文档，并称最后的文档为MRD。
         在这种情况下，MRD包括本段描述的内容，也包括上一段描述PRD的内容，并且可
         能超过50页。

- FSD :: Functional Specifications Document，功能详细说明。有一点像“概要设计”，
         这步就开始往开发衔接了，产品UI、业务逻辑的细节都要确定，细化文档并保持
         更新。相应的，有很多内容，比如表结构设计，要由项目经理来编写了。

         功能规格文档（FSD）把焦点集中在实现，定义产品功能需求的全部细节。FSD可
         能通过一张张的截屏和一条条功能点来定义产品规格。这是一份可以直接让工程
         师创建产品的文档。与MRD和PRD侧重于以市场需要和产品角度看需求不同，FSD把
         重点放在了以表格形式定义产品细节，再让工程师实现这些细节。FSD也可能包括
         完整的屏幕截图和UI设计细节。FSD通常是由拥有产品分析师，工程领导或者项目
         经理头衔的人撰写的

- PSD :: Product Specifications Document，产品规格文档（PSD）是一个较不流行的缩
         写，但是在有这样一个文档的机构中，它大体和上面描述的功能规格文档（FSD）
         相同。

- SRS :: Software Requirements Specification，软件需求文档，软件需求文档（SRS）
         是另一较不流行的缩写，在创建SRS的机构中，它在内容和细节上和上面描述的
         PRD或FSD有些想像。

- ROI :: Return On Investment，投资回报。原本是会计学概念，早期用来判定投资工厂
         或购买铁路相关的成本是否合理，现被广泛使用在各个领域。ROI的结果通常用百
         分比来表示，即投入产出比，简单来说就是企业所投入资金的回报程度。ROI计算
         公式为：收益/投资×100%或者ROI=（成本降低+收入增长）/总成本。相关的术语：
         资金回收期，IRR（内部收益率）等等。

     　　投资报酬率，计算公式为： =ROI = (1 + g) * n / PER= 。

         其中，g代表企业未来n 年平均获利成长率。PER表示本益比。若个别企业的ROI大
         于同业平均投资报酬率，则该企业值得投资。

- CPA :: Cost Per Action，次行动的费用，即根据每个访问者对网络广告所采取的行动收
         费的定价模式。对于用户行动有特别的定义，包括形成一次交易、获得一个注册
         用户、或者对网络广告的一次点击等。

- ASP :: Average Selling Price，公司某一类型产品或全部产品的平均销售价格（或称出
         厂价格）。公式为：销售额÷出货量。

         平均售价是分析预测制造业公司销售收入和毛利率的重要指标，是投资者需要密
         切跟踪和计算的经营数据。在销量不变的情况下，平均售价提高可以增加销售收
         入和毛利率，在销量下降的情况下，如果公司能提高平均售价可以降低销售收入
         和毛利率下滑的程度，当然，最好的情况是价升量增，销量和售价都出现增长。
         公司产品平均售价提升主要来自于产品结构的改善，如彩电生产企业近年来产品
         平均售价增长就是因为高价格的平板电视销售比重显著提升。所以，把握制造业
         公司业绩增长的两项最重要的因素就是产品销量和平均售价的变化。
