#+title: 13个不容错过的Java项目
#+date: <2016-09-22 20:48>
#+filetags: java reprint


今天我们将整理一大波干货满满的Java示例代码与能力展示素材。

GitHub可谓一座程序开发的大宝库，有些素材值得fork，有些则能帮助我们改进自有代码或
者学习编程技能。无论如何，开发工作当中我们几乎不可能绕得开GitHub。

下面，我们将一同分享各有趣且颇为实用的Java库，大家请任取所需、不用客气~

* 1.极致精简的Java

Bootique是一项用于构建无容器可运行Java应用的极简技术。该项目允许大家创建REST服务、
Web应用、任务、数据库迁移等等，且一切都立足于模块实现。另外，大家也可以将其作为
简单的命令进行使用。

该项目的目标在于将应用从Java容器中解放出来，允许开发者重新回归main()方法。另外其
中还包含部分内置命令，因此就算各位需要处理的代码量不多或者并未向应用中导入任何模
块，仍然能够利用Bootique对其加以执行。

* 2.优雅的问题处理方式

99-problems，光看名字就能对其功能了解一二。很明显，它的作用是帮助大家磨练逻辑编
程中的具体技能。大家可以选择利用Java 8、Scala或者Haskell进行问题解决，并最终找到
最精致的解决办法。

如果大家喜爱解题，其中还提供多种不同层级的难度供各位选择。另外，如果大家将全部99
道难题解决掉，则可进一步冲击Java Deathmatch。如果大家被难住了，请点击此处查看难
题——但请注意，认真思考之后再参阅比较好哦。

* 3.字符串操作

Strman-java库是一套Java 8库，专门用于处理字符串。由于其可用于Maven，因此大家只需
要面向选定的构建工具添加关联性即可使用。

如果大家使用过Kik并听说过其遭遇的leftPad问题，那么Strman可能是个更好的选择——其能
够返回特定长度的新字符串，且自动填充开头部分内容。另外，其中还提供一整套功能列表，
包括向值附加字符串、从特定目录中提取字符以及利用字符串在开始与结束间返回数组等等。

* 4.数据浏览

如果大家希望通过酷炫的方式进行数据交互，那么Dex绝对不容错过。它能够帮助我们提取、
转换及可视化数据，同时附带预测功能。大家可以将可视化结果发布为3D或者其它HTML变量
形式。

Dex允许我们生成超过50种不同的可视化模式，其中包括世界地图、参与时间表、网络使用
情况等。大家也可以利用R与其运行实例相结合，从而构建起复杂的统计分析与预测分析体
系。

* 5.小小大数据

Tablesaw是一套内存内数据表，其中包含多种数据工具与面向列的存储格式。其设计思路认
为没人会面向小型任务执行分布式分析，而大家可以在单一服务器上对200万行级别的表进
行交互。

大家能够利用Tablesaw执行各种规则，从而检查显示布局、数据优先级或者针对数据显示及
交互向特定用户提供扩展控制范围。在它的帮助下，我们可以利用RDBMS与CSV文件导入数据，
添加及删除列，执行映射与规约操作或者将表保存在经过压缩的列式存储格式当中。

* 6.键值存储

Chronicle Map是一套内存内键值存储方案，其设计目标在于实现低延迟与/或多进程应用，
例如贸易与金融市场应用。这套库主要面向中等读取与写入查询延迟场景，允许用户根据服
务器中的硬件执行线程数量编写合适的查询机制。

其主要用途包括在单一服务器（例如Redis）中替代低速键值存储方案，或者取代同类面向
JVM的解决方案以实现速度提升。大家也可以将部分应用状态移出Java堆，从而降低堆体积
及GC压力。

* 7.负载调查工具

Gumshoe允许大家监控自己的应用性能统计指标。有了它，我们可以精确到具体代码行并了
解与堆栈调用及个别栈帧相关的统计数据，从而确切分析资源使用情况（例如TCP、UDP、文
件系统或处理器使用量）。

这套库能够在统计数据生成时对其进行捕捉、过滤与可视化处理，从而更为直观地实现数据
结论查阅。如果需要更为具体地使用，大家还可以在数据捕捉与/或可视化处理过程中过滤
栈帧，并在其运行中加以变更。

* 8.Java音乐

SoundSea允许大家搜索并下载歌曲。其内置有元数据与专辑信息，大家在查找特定歌曲时，
SoundSea会在iTunes上查找相关元数据与专辑信息，并显示相关结果。如果匹配的歌曲超过
一首，大家可在其中找到自己需要的条目。

歌曲本身下载自Pleer.com，大家还可以根据高品质、低品质或者VBR码率进行过滤。这同时
也是一款迷你播放器，供我们直接聆听歌曲而不再经由其它音乐库。


* 9.检查泄漏问题

LeakCanary是一套开源库，旨在帮助我们解决内存泄漏问题。大家可以利用它在Java（与
Android）中检查内存泄漏。正如其GitHub页面中所言，“千里之埋溃于蚁穴”。

在LeakCanary设置完成后，大家可以利用其自动检查泄漏并在发现问题时给出通知。

* 10.多维数组

ND4J是一套开源库，能够将多种来自Python社区的科学计算工具引入JVM。其面向生产环境
设计，因此运行速度很快但对内存容量却要求不高。在它的帮助下，工程师们能够轻松将算
法及接口移植到Java与Scala库当中。

这套库的主要贡献是提供一套通用型n维数组对象，其多平台功能包括GPU与线性代数外加信
号处理能力。其与Hadoop及Spark相集成，且提供API以模拟Numpy——一款高人气Python数学
库。

* 11.监控Java

无论大家使用哪种监控工具，Automon都能够将其与AOP（AspectJ）相结合以实现Java代码、
JDK以及依赖库监控声明。其可与其它各知名监控工具相协作，例如JAMon、JavaSimon、
Yammer Metrics以及StatsD等，同时亦支持各类日志记录库，包括perf4j、log4j、sl4j等
等。

另一款出色的生产型监控工具为Takipi。它能够帮助大家了解自己的代码何时及为何发生崩
溃，查看全部意外状况并获取与之相关的全部堆栈、源与状态信息。

* 12.打理Java

这套库允许我们对目标JVM的CPU线程使用情况进行池化，同时定期向控制台报告实时CG信息
并提供基础样本分析功能。在这里，我们可以通过命令行配合MBean执行各基本操作，同时
将目标Java进程的全部MBeans转储为JSON格式。

Jvm-tools，或者SJK，是一套用于JVM故障排查、监控与配置的工具组合。这是一款不像话
地工具，使用JVM的标准诊断接口（例如JMX、JVM attach与perf计数器），同时添加了更多
逻辑以应对各类常见故障排查用例。

* 13.最佳Java

awesome-java是一套出色的Java框架、库与软件合集。如果大家不太清楚自己应当如何选择
具体方案，请务必参考这套清单 ，其中甚至根据类别对各条目加以划分。

其中还包含一部分仍在使用的古老工具，包括能够简化映射的框架，可构建应用周期与依赖
性的工具以及负责处理字节码编程的库等等。

* 总结陈词

这当然只是GitHub的冰山一角，毫无疑问还有更多项目值得大家审视并用于改善自身代码工
程。也欢迎大家结合自己的经验在评论中提供更多推荐！
