# -*- coding: utf-8-unix; -*-
#+TITLE:       出师表
#+AUTHOR:      Bruce Asu
#+EMAIL:       bruceasu@163.com
#+DATE:        <2010-10-04 10:24>
#+filetags: knowledge
#+DESCRIPTION: 出师表 粤语翻译

#+LANGUAGE:    en
#+OPTIONS:     H:7 num:nil toc:t \n:nil ::t |:t ^:nil -:nil f:t *:t <:nil

* 原文

先帝创业未半而中道崩殂，今天下三分，益州疲弊，此诚危急存亡之秋也。然侍卫之臣不懈
于内，忠志之士忘身于外者，盖追先帝之殊遇，欲报之于陛下也。诚宜开张圣听，以光先帝
遗德，恢弘志士之气，不宜妄自菲薄，引喻失义，以塞忠谏之路也。

宫中府中，俱为一体，陟罚臧否，不宜异同。若有作奸犯科及为忠善者，宜付有司论其刑赏，
以昭陛下平明之理，不宜偏私，使内外异法也。

侍中、侍郎郭攸之、费祎、董允等，此皆良实，志虑忠纯，是以先帝简拔以遗陛下。愚以为
宫中之事，事无大小，悉以咨之，然后施行，必能裨补阙漏，有所广益。

将军向宠，性行淑均，晓畅军事，试用于昔日，先帝称之曰能，是以众议举宠为督。愚以为
营中之事，悉以咨之，必能使行阵和睦，优劣得所。

亲贤臣，远小人，此先汉所以兴隆也；亲小人，远贤臣，此后汉所以倾颓也。先帝在时，每
与臣论此事，未尝不叹息痛恨于桓、灵也。侍中、尚书、长史、参军，此悉贞良死节之臣，
愿陛下亲之信之，则汉室之隆，可计日而待也。

臣本布衣，躬耕于南阳，苟全性命于乱世，不求闻达于诸侯。先帝不以臣卑鄙，猥自枉屈，
三顾臣于草庐之中，咨臣以当世之事，由是感激，遂许先帝以驱驰。后值倾覆，受任于败军
之际，奉命于危难之间，尔来二十有一年矣。

先帝知臣谨慎，故临崩寄臣以大事也。受命以来，夙夜忧叹，恐托付不效，以伤先帝之明，
故五月渡泸，深入不毛。今南方已定，兵甲已足，当奖率三军，北定中原，庶竭驽钝，攘除
奸凶，兴复汉室，还于旧都。此臣所以报先帝而忠陛下之职分也。至于斟酌损益，进尽忠言，
则攸之、祎、允之任也。

愿陛下托臣以讨贼兴复之效，不效，则治臣之罪，以告先帝之灵。若无兴德之言，则责攸之、
祎、允等之慢，以彰其咎；陛下亦宜自谋，以咨诹善道，察纳雅言，深追先帝遗诏，臣不胜
受恩感激。

今当远离，临表涕零，不知所言。


* 译文一
你伯爷出来行，半路就去咗卖咸鸭蛋，睇个势，依家个地盘分成三嚿，益州睇来都系保唔住
嘅嘞，以后个世道睇来都几难挨。但系你伯爷留低班细嘅都好忠心，班懵柄出去劈友连命都
唔要，呢D都系睇在你老豆以前俾钱又俾女的份上，现家想报答返你啫。

嗱，阿叔我现家就只系想你醒醒定定，搞掂你老豆嘅遗愿，等D兄弟都有得威;千祈唔好将自
己当成一嚿叉烧，辜负咗班手足。

家吓班兄弟都系自己友嚟，想闹边个掴边个，都要公平；唔俾心机做嘢嘅，成日系度搞三搞
四嘅，同埋份人忠忠直直嘅，就交俾保卫科，应该斩手既斩手，应该升职嘅就升职，甘样就
表现到你对大家都系公平嘅，你千其唔好帮埋一边，对大家大细超。


郭仔、费仔、董仔，份人都好老实，做嘢好周到，你爷伯在世个时就特别睇得起佢哋，临死
前叫佢哋好好帮扶你，阿叔我话斋，会里面大大细细嘅 事情都可以交俾佢地；你个个懵柄
向叔，人好好，亦都好生猛，劈得玩得，你伯爷都话佢“掂”，你得就提拔一下，我觉得收陀
地劈友嘅事就交俾佢，一定可以搞大我地个地盘，以后就冇人敢惹我地架嘞。

我地旧阵时个会点解开始甘劲呢，就系因为一直收埋D老实人，赶走D呃饮呃食嘅，后来点解
会搞到甘衰，就系因为身边剩番班口噏噏当秘笈嘅废人，你伯爷以前次次同我倾计，讲起呢
单嘢都赤赤痛。侍中、尚书、长史、参军，呢几条友都系阿叔我斩过鸡头嘅好兄弟，你一定
要信佢哋，我哋会重振雄风之日就指意晒你嘞!

阿叔本来就系个耕田佬，系南阳都有番几嚿田，在呢个人怼人既时代，我不想怼人，只系想
唔俾人怼。你伯爷唔嫌弃我，三日唔埋两日就走去我屋企，问我点搞好个会，阿叔我就感激
到标晒马尿，咁就跟咗你老豆啦。后来我哋会同你个艾呀舅父权爷个会开片，衰咗，阿叔我
撑住成个会，到现家都廿几年罗。

你伯爷知道阿叔我醒目，所以卖咸鸭蛋之前就将大事都交托晒俾我，自从换左你做阿头之后，
我就日日失眠，担心辜负左大佬嘅心意，所以五月个时就带住班手兄开船过河，去个个山卡
啦嘅地方，搞掂晒所有应该搞定嘅野。依家南边无人再敢搞三搞四，我地班靓又人强马壮，
应该好好地俾班手足疏弗下。然后再将中原打番番黎，将个D冇本心嘅二五仔通通做低晒，
将我地个D忠字头嘅都扶番起身。咁样我就算对得你伯爷住啦。至于要点搞，冧桥呢D甘嘅野
就要靠攸之、 祎仔、允仔佢地嘞。


呢一次阿叔我就系去劈班契弟，劈唔成嘅话你话点就点。如果搞唔掂个会，你就去搵攸之、
祎仔、允仔，我就唔信个班野敢吃碗面反碗底。阿仔你都应该揾个时间好好地甘谂下你伯爷
既话。甘你阿叔我就好欣慰啦。得啦得啦，时间到，去劈友啦，男人老狗，标晒马尿甘，都
唔知讲左D乜野。


* 翻译二
我同你讲：你伯爷捞世界捞到一半就拉佐柴。宜家个场又分成三忽，益州又就快俾人掠埋，
伽下真系几大锅。好彩你老豆班o靓够姜，劈起友黎唔要命，你估佢地为你啊？！俾面你老
豆咋！所以唔好话我话你丫，系识捻个就的起心肝搞好个社团佢，咪搞到你老豆死都唔眼闭
啊。唔好成日以为自己成只狗咁，班契弟个个都睇你头嘎，唔好俾面唔要面！
      

屋企同场口都系你地头，边条死铲唔识做就打七佢，千祈唔好就住就住。下面班o靓见到就
无晒嘢讲啦。

好似丧郭啊、费爷啊、老董啊佢地都系你死鬼老豆D手足，得闲就同佢地斟下，无坏既。向
宠条契弟虽然霎下霎下，但系死得佢又几识捞，你死鬼老豆旧时都几睇重佢嘎。有时间同佢
饮下茶，有着数实会预埋你。

知唔知点解先汉咁风生水起，就系因为班废柴俾人斩晒！你死鬼老豆讲翻起真系丧到头都白
晒。
      

唔怕同你讲，你世伯我原先系南阳耕田嘎咋，个势立立乱，好彩就话执翻条命仔，捻都无捻
过出黎行。难得你死鬼老豆唔嫌我缩骨，日日黎痴饭食，问哩问路，你老味仲烦过伯爷婆，
我顶佢唔顺唯有出黎陪佢捞世界。后尾俾人踩场系我出去顶，俾大耳窿追数又系我出去顶，
顶下顶下都成二十几椂咯。

你个死鬼老豆知我有料，死唔断气都要交晒D生意俾我，日又捱夜又捱，又惊死捞得唔好你
老豆半夜翻黎搵我，咪系五月份带班o靓过大海，你老味果度毛都唔多条！宜家下好啦，南
边个场俾我地摆平左，班契弟又搵晒架撑，你好去劈友啦。

边个扑街唔死远就斩开佢几十椂，掟落咸水海喂鲨鱼，将我地个场攞晒翻黎。嗱，你死鬼老
豆就交带我咁多嘞，其他你去搵我之前讲果几条友喇。

世侄，我帮你劈埋今次友，捞唔掂你就捉我去祭旗。如果个场口唔够旺，就去屌臭丧郭果几
条茂利。其余你食自己啦！

我就走嘎啦，写呢篇嘢真系写到成壳眼泪鼻涕，都唔知写紧乜，你自己执生。
