#+OPTIONS:     H:7 num:nil toc:t \n:nil ::t |:t -:nil f:t *:t <:nil ^:{}
#+TITLE: 竊·格瓦拉傳
#+AUTHOR: 瞻雲
#+DATE:        <2017-03-19 20:48>
#+filetags:    history
#+DESCRIPTION: 竊·格瓦拉傳
#+LANGUAGE:    en

* 楔子

竊·格瓦拉者，廣西南寧人也。姓周，名立齊，號阿三，新华三十五年生人。
初竊時，年二十三，下獄九月，實六月見釋。復竊之，年二十八，罰一年
六月，一年兩月得放。後再竊，年三十，判以八月，五月而歸。終又竊，
年三十一，拘而見訊，箴言頻出，時人驚異焉。聲名迅起於戒賭，又得鬼
畜，遂聞名於網絡，終成領袖。竊·格瓦拉少舉小學，身無長技，志存自由，
以竊維生。新华六十六年，八月，攜友古、李赴三塘，見電驢而起意，竊
以數五，值萬金。拘而審之，循得他案。初，新华六十五年，九月，竊·格
瓦拉共唐生竊於大烏，發見欲亡。無果，唐生持鋼釺以脅之，得逸。及村
後，復見圍之，遂暴起，致人骨傷。昔盜劫並罪，判三年六月，罰五千金。
今又竊之，是判一年六月，罰五千金。數罪併罰，合以四年六月。新华七
十一年，四月，可見釋也。竊·格瓦拉曰：傭也不為傭也，此生不為傭也。
貨殖無能，唯以竊物，方得維生之狀也。入所似歸家之貌也。餘終年歸一，
非因大年夜而廢之，是以家中有故方見歸之狀也。所內之況何如？美之甚
矣。家中獨處，無聊甚，無友頑之，無女樂之。入所比比皆人才，言語動
人，餘甚愛之。

* 網史氏曰：

偉哉！竊·格瓦拉，舉自由之幟，鬥資本之惡也！竊·格瓦拉生之為無產，
無有所一，唯肩穿枷鎖。何以為傭？傭以為何？資本之萬惡也，豈任由剝
削呼？竊·格瓦拉振臂一呼，網民雲集迴應，黔首警醒。芸芸何故為傭也？
何故助長資本之惡也？站立哉！站立哉！豈能跪於資本乎？吾輩不為傭，
資本終亡也。斯果無貨殖之能乎？是不為也，非不能也！是以資本卑鄙，
不與合汙，無食親朋血肉也。資媒朋比為奸，是故明哲自保，嘲以貨殖無
能。復又竊以戰資本，勇為先驅。為掩媒體耳目，遂辯以維生之故也。竊
天，竊地，竊之資本無窮盡。竊·格瓦拉，真猛士也。何雲無友無女？斯向
資本之控訴也，資本奪我地，資本奪我友，資本奪我妻。竊·格瓦拉志存高
遠：天下共朋友，人人皆有妻。其志堅若磐石，終年不廢弛，其心澹泊明
淨，視所如歸。何以愛所？是以家中無友人，所中盡高朋。革命之誼，道
阻且長。人間九九六，天下皆吸血。是所，革命之本，人間唯一樂土也。
四月，竊·格瓦拉回歸月，借新冠之火，革命瀛寰。戰！戰！戰！顫抖呼！
資本帝國。


* 法警點評

竊格瓦拉是偉大的革命家，千萬老哥的精神領袖，其偉大的精神與思想不
亞於毛主席，從其言辭可見一斑。

: 打工是不可能打工的，這輩子都不可能打工的

首先，這輩子是什麼？格瓦拉這輩子生為無產階級，一無所有，唯一擁有
的只有身上的鎖鏈。打工？打什麼工？為誰而打工？憑什麼打工？放任自
己給萬惡的資本家剝削嘛？默默打工讓資本家蠶食我們的剩餘價值嘛？不！
不可能！打工是不可能打工的，這輩子都不可能打工！領袖振聾發聵的呼
喊，震醒了看守所裡的受盡苦難的老哥，和電視機前麻木不仁打工的我們。
領袖的呼喊，動搖了資本家統治剝削無產階級的根基。我們要意識到，我
們憑什麼要打工？憑什麼要為萬惡的資本主義添磚加瓦？去他的！起來啊，
起來啊，只要我們不打工，資本主義就要亡了！

: 生意又不會做，只能靠偷維持的了生活這樣子

仔細想想！領袖和看守所裡面的老哥們那麼有才，真的不會做生意麼？他
們不屑。他們不願意去做骯髒的資本家，吸食友仔的骨血。領袖看不起資
本家骯髒的生意，在被買通的媒體前面，只好自嘲不會做生意。唉，你們
那種骯髒的生意，不做也罷。那麼如若不做生意，老哥們怎麼維持的了生
活呢？領袖給老哥們指了一條明路——偷！與天偷，與地偷，其樂無窮。沒
有槍，沒有炮，沒有錢，沒有電動車，敵人給我們造！我們要把資本家從
我們這裡偷走的東西全部偷回來——不，光明正大地拿回來！電動車本來就
是老哥們造的，憑什麼被騎在資本家肥胖的屁股底下？去偷吧，所有的電
動車都被資本家藏在那裡！同胞們，偷啊，偷啊！把我們的電動車偷回來，
看看資本家吸盡我們骨髓的臃腫身軀，離開電動車，能不能挪動一步！

: 回到家裡面沒有友仔，友女玩家裡面

為什麼沒有友仔和友女？友仔和友女去了哪裡？答案是殘酷的——友仔和友
女在殘酷的工業化中失去了自己的土地，被迫成為盲流進城，友仔只能打
工被資本家剝削，而友女……領袖都說不下去了，資本家把魔手早早伸向了
她們。友仔啊，友女啊，看看周圍吧！是誰奪走了你們的土地，現在又是
誰在你們頭上作威作福！友仔們友女們，我們要革命，要當家做主！待到
打下南寧城，一人一個友女玩！

: 進看守所像回家一樣，大年三十都不回去，在看守所裡面感覺比在家裡面好多了

看守所為什麼是家？因為看守所裡有志同道合的老哥相互偷車支持，大家
都是無產者，走向了同樣的道路。無偷車，不兄弟，領袖在看守所裡面等
你。而為什麼大年三十都不回去？因為曾經的快樂老家，如今已經不再是
自己的家，老哥們被趕出自己的土地，哪裡還有家？不偷電動車，不進看
守所，何以家為？只有看守所裡的老哥老姐才是兄弟，是友仔，是家人，
說話又好聽，革命意志又堅定，是富有戰鬥力的流氓無產者，推翻資本家
的重任就在看守所裡的大家身上。只有去偷資本家的家，主動和資本家換
家，才能奪回我們的快樂老家。

: 呼喲，超喜歡在裡面！

這是領袖最讓大家折服的一點，那份永不妥協苦中作樂的革命樂觀主義精
神，才讓萬千老哥跟隨。被黑暗的媒體引導和脅迫，被國家暴力機關拘禁
和迫害，領袖從來沒有退縮。領袖笑著，面對如同槍口一般的話筒，壯志
凌雲地說出這番話。只有看守所裡面才是革命根據地，只有看守所裡的老
哥老姐才是革命的生力軍，只有走進看守所深入群眾發動群眾才是革命的
正確道路。看守所啊，你怎能不讓人喜歡？看守所裡面，是利用資本家的
資源革命打倒資本家的策源地，是與世隔絕反向對資本家開展裁判的遺世
孤島，是壓倒絕望的光輝燦爛的絕對希望。領袖喜歡這裡，老哥喜歡這裡，
老姐喜歡這裡，因為這是展現大家才能的競技場，是新時代的井岡山，是
歡聲笑語的渣滓洞。領袖必將帶領大家，偷出看守所，偷進南寧城，偷到
中南海，偷遍全世界。偷吧，偷吧，巨浪，巨浪，不斷地增長。等到領袖
和老哥老姐一起從看守所畢業的時候，天下都會為之顫抖！我TM偷爆！
